### ISSUE TITLE
Discord Snap is out of date

### ISSUE THREAD

**Issue by YamiYukiSenpai** [snapcrafters/discord#49]
I got a pop up asking me to download either the `.deb` file or the `.tar.gz` file.  It won't let me use it if I click "I'll figure it out".

![screenshot_20190115_143915](https://user-images.githubusercontent.com/13153124/51205192-571a0580-18d3-11e9-9888-fc90187bdade.png)

I ran `# snap refresh`, and everything's up-to-date.  In addition, according `snap info discord`, last refresh was yesterday.

**Comment by Larry1123** [comment]
There is an older issue #27 that is still open from another time this happened. Not sure if it was just forgotten to be closed or what, but it's there too.

**Comment by zesaver** [comment]
Also got affected

**Comment by Larry1123** [comment]
As far as I can tell the build triggered yesterday https://build.snapcraft.io/user/snapcrafters/discord/431694 installed version 0.0.5 the latest being 0.0.7.

**Comment by alex1a** [comment]
+1 Ubuntu 18.04

**Comment by soundconjurer** [comment]
Yeah, same issue. Too bad there isn't a way of keeping it up to date as they release it from a snap in essentially real time.

**Comment by d2dyno** [comment]
Same issue here now as well.

**Comment by pcewing** [comment]
+1 on 18.10

**Comment by camdixon** [comment]
+1 here too.

How can developers like me contribute to keep this snap updated?   I need to find resources on how this builds and contribute to it.

**Comment by kz6fittycent** [comment]
> +1 here too.
> 
> How can developers like me contribute to keep this snap updated? I need to find resources on how this builds and contribute to it.

You can clone this repo, then perform a PR when you work out a fix. I'm sure they'd appreciate it.

**Comment by EndrII** [comment]
version **0.0.8** is already available, and the repository is still **0.0.5**
when to wait for the update ?

**Comment by vish9u** [comment]
ubuntu 16.04 and ubuntu 18.04. done uninstalling and reinstalling it. same update page is being shown.

**Comment by Gunni** [comment]
This is a blocker, app cannot be used in its current state.

**Comment by s4Ne1** [comment]
+1 on Ubuntu 18.04. :(

**Comment by MadeByNC** [comment]
reinstalling discord doesnt help.

from today

snap install discord
discord 0.0.5 from Snapcrafters installed

**Comment by deviousgeek** [comment]
Only solution for me to was to use the tarball to install. :(

**Comment by paraiko** [comment]
I guess that this issue is not so much technical, but more procedural and maybe should be solved at that level as well? It seems that Discord chooses to distribute its software via its own mechanism of choice (deb package / tarball) including an update mechanism. 
This whole construct is nicely snapped up in the snap package by the snapcraft team. However this means that the team always has to play a catchup game if Discord updates its client and/or its method of distribution. 

The solution would be to convince discord to distribute their software as snap and/or flatpack, or to convince them to give the snapcraft team prior notice of an upcoming update so the snap can be updated timely? 

BTW for me (ubuntu 18.04.1) works fine to install the discord .deb package. however this means that I now have to versions of discord installed. a snap version that does not work and a .deb version that is updated to 0.8. I guess this is hard to explain to the average user....

**Comment by rigred** [comment]
We might need to consider adding a workaround to skip the update check for the discord snap.
On my laptop I still have the discord snap open and it continues working fine on the 0.0.5 version.
But on my desktop I rebooted and of course now I can no longer get into discord since the update check blocks use of the app even though it does still work as I can see from my laptop.

Potentially adding a workaround to skip the update check on the snap version should be a feature to consider (if it's at all possible) to ease the update transition period. 
That said on the snap the update check blocker is essentially useless anyway since by snap design it must be updated on the repo. 

Note, mine is now reporting version 0.0.8 already? Yesterday it was 0.0.6, then 0.0.7. Now 0.0.8 - what sort of rollout is this?
![image](https://user-images.githubusercontent.com/5716332/51250933-b134cc80-19a0-11e9-8560-d1e5b36793f3.png)

**Comment by Larry1123** [comment]
The fix seems as simple as running the build again. It looks like it had just built too soon for the discord download api endpoint to return the newer download. Can someone that is able to do that trigger a build?

**Comment by rigred** [comment]
@Larry1123 Correct
Just built it myself as a snap locally. Works beautifully
It literally just has to be rebuilt. Going to happen soon

**Comment by rigred** [comment]
Also I'm not affiliated with this at all - 
I'm just winging it and learned snaps and snap building 30 minutes ago to get myself updated :D

**Comment by rigred** [comment]
Spoke too soon - it segfaults on something. Probably a dependency change.

**Comment by YamiYukiSenpai** [comment]
0.0.8 showed up on edge channel

Seems fine so far

**Comment by DheathNone** [comment]
The edge installs fine and discord updates a few files after launch. It launches fine but when a channel or private conversation is selected it fails with:
Failed to generate minidump.zsh: segmentation fault (core dumped)  discord

**Comment by YamiYukiSenpai** [comment]
@DheathNone oh you're right
I just launched it, and left it, so I thought it was fine

**Comment by EndrII** [comment]
``` bash
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Discord 0.0.8
Starting updater.
[Modules] Modules initializing
[Modules] Distribution: remote
[Modules] Host updates: enabled
[Modules] Module updates: enabled
[Modules] Module install path: /home/endrii/snap/discord/85/.config/discord/0.0.8/modules
[Modules] Module installed file path: /home/endrii/snap/discord/85/.config/discord/0.0.8/modules/installed.json
[Modules] Module download path: /home/endrii/snap/discord/85/.config/discord/0.0.8/modules/pending
[Modules] No updates to install
[Modules] Checking for host updates.
[Modules] Host is up to date.
[Modules] Checking for module updates at https://discordapp.com/api/modules/stable/versions.json
[Modules] No module updates available.
Failed to generate minidump.Ошибка сегментирования (стек памяти сброшен на диск)
```

1. after launch, the application is very slow
2. after clicking on the chat with a friend the program crashed

**Comment by EndrII** [comment]
and not showing on tray menu
![default](https://user-images.githubusercontent.com/12465465/51275074-f7f6e680-19e1-11e9-9ef6-913fb354b088.png)
OS: ubuntu 18.04

**Comment by YamiYukiSenpai** [comment]
@EndrII mine's there, but it's extremely tiny

OS: Kubuntu 18.10
