### ISSUE TITLE
"Discord": snap not found (raspbian command line install error)

### ISSUE THREAD

**Issue by porkupinexe** [snapcrafters/discord#56]
I'm trying to get discord to run on my Raspberry Pi Model 3 b but for some reason the command line install doesn't work
"sudo snap install discord
error: cannot install "discord": snap not found"
The first command is lifted directly from the snapcraft store, but for whatever reason it seems to think Discord doesn't exist
I'm running both the latest version of Raspbian and snap so I have no idea what the issue is

(be gentle I'm new)

**Comment by Fuseteam** [comment]
its probably because there is no arm build of discord and raspberry pi is an arm device

**Comment by porkupinexe** [comment]
@Fuseteam that was something that I thought, but that doesn’t make sense. Why would it say that it doesn’t exist rather than saying that it’s unsupported? And even if it were unsupported I should still be able to download the files, it just wouldn’t run on my device.

**Comment by popey** [comment]
Thanks for reporting the issue @porkupinexe 
It is indeed because there is no arm build for Discord. Discord themselves provide no build of their application for the ARM architectures, only for 64-bit x86 architecture. The snap command line tool says it doesn't exist because from the perspective of that device, it's true. there's no Discord snap which would work on that machine.
