### ISSUE TITLE
Discord bin is not correct

### ISSUE THREAD

**Issue by snex** [snapcrafters/discord#90]
`snap install discord`

Click the icon in gnome, nothing happens.

Run `discord` from command line: `Bus error (core dumped)`

`which discord` gives `/snap/bin/discord` which is a symlink pointing to `/usr/bin/snap`

This seems wrong. If I hunt down the actual binary file at `/snap/discord/115/usr/share/discord/Discord` then it runs.

**Comment by snex** [comment]
I think I see the issue - the .desktop file has this line:

`Exec=/usr/share/discord/Discord`

There is no such file on my file system.

**Comment by Fuseteam** [comment]
/snap **is** a symlink to /usr/bin/snap that is normal also snaps are confined so `/usr/share/discord/Discord` is actually in `/snap/discord/current/usr/share/discord/Discord` so that's probably not and issue as to the snapped app `/snap/discord/current/` is the root

have tried relaunching after it failed? something else might've gone wrong the first time

**Comment by snex** [comment]
Yes, I have tried re-launching, as well as uninstalling/reinstalling. It seems that the desktop icon has an incorrect path as per my second comment, since `/usr/share/discord/Discord` does not exist at all. Other snaps work, and their desktop icons have an `Exec` line that points to a file that actually exists.

**Comment by popey** [comment]
Apologies for the delayed response.
@snex I'm not seeing this here. 
```
alan@mcp:~$ grep Exec /var/lib/snapd/desktop/applications/discord_discord.desktop 
Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/discord_discord.desktop /snap/bin/discord
```
